name: Recording_pen
description: "Recording Pen"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: 3.29.0

flutter_native_splash:
  # 启动页的背景颜色
  color: "#000000"
  # 启动页图标
  image: "images/welcome.png"
  # 手机操作系统大于等于12时需特殊设置
  android_12:
    image: "images/welcome.png"
    icon_background_color: '#000000'
#  android_11:
#    image: "images/welcome.png"
#    icon_background_color: '#ffffff'
#  android_10:
#    image: "images/welcome.png"
#    icon_background_color: '#ffffff'
#  android_9:
#    image: "images/welcome.png"
#    icon_background_color: '#ffffff'

  android: true
  ios: true

  android_gravity: top
  ios_content_mode: top

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  get_storage:
  wakelock_plus: ^1.2.8
  flutter_blue_plus: ^1.34.5
  logger: ^2.3.0
  encrypt: ^5.0.3
  device_info_plus: ^10.1.0
  package_info_plus: ^8.3.0
  shared_preferences: ^2.2.3
  crypto: ^3.0.3
  network_info_plus: ^6.0.1
  permission_handler: ^11.3.1
 
  dropdown_button2: ^2.3.9 #下拉菜单
  flutter_local_notifications: ^17.2.2
  flutter_timezone: ^3.0.1
  path_provider: ^2.1.4
  event_bus: ^2.0.0
  uuid: ^4.5.0

  flutter_svg: ^2.0.10+1

  date_format: ^2.0.9

  auto_size_text: ^3.0.0

  intl: ^0.19.0
  flutter_localization: ^0.2.2

  flutter_native_splash: ^2.4.4

  flutter_blue_plus_windows: ^1.26.1
  window_manager: ^0.4.3

  flutter_easyloading: ^3.0.5

  wifi_iot: ^0.3.19+2

  opus_flutter: ^3.0.3
  opus_dart: ^3.0.1

  flutter_pcm_sound: ^3.1.7
  app_settings: ^6.1.1
  file_picker: ^10.2.0
  pager: ^0.0.6

  seilon_dnr:
    path: ../seilon_dnr

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13 #编译
  hive_generator: ^2.0.0 #用于生成对象存储适配器文件

  flutter_lints: ^3.0.0
  flutter_gen_runner: ^5.8.0
  flutter_launcher_icons: ^0.14.3


flutter_launcher_icons:
  android: true
  ios: true
  image_path_ios: "images/app_icon.png"
  image_path_android: "images/app_icon.png"

flutter:
  assets:
    - images/
    - bin/
  #    - images/Image.svg
  #    - images/Image.png

#  fonts:
#    - family: Roboto
#      fonts:
#        - asset: fonts/Roboto-Light.ttf
#          weight: 700
#    - family: Logo
#      fonts:
#        - asset: fonts/test.ttf
#          weight: 700



  uses-material-design: true
flutter_intl:
  enabled: true

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true
    rive: true
    lottie: true
